name: Build ROCK

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
  schedule:
    - cron: "0 12 * * 0"

jobs:
  build:
    uses: canonical/observability/.github/workflows/build-rock.yaml@more-tags
    secrets: inherit
    with:
      rock-name: cos-alerter
      tag-minor: true
