name: Push to Main

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  version-check:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.check-version.conclusion }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check Version
        id: check-version
        continue-on-error: true
        run: |
          version=$(grep -P -o 'version = "\d+\.\d+\.\d+"' pyproject.toml | grep -P -o '\d+\.\d+\.\d+')
          tags=$(git tag -l '*.*.*')
          echo ${tags} | grep -w -q ${version}

  python-package:
    runs-on: ubuntu-latest
    needs: version-check
    if: needs.version-check.outputs.status != 'success'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
      - name: Install Build Tools
        run: pip install --upgrade build twine
      - name: Build
        run: python3 -m build
      - name: Upload
        run: |
          python3 -m twine upload \
          --verbose --non-interactive \
          --username __token__ --password ${{ secrets.PYPI_TOKEN }} \
          dist/*
  rock:
    uses: canonical/observability/.github/workflows/build-rock.yaml@main
    needs: python-package
    secrets: inherit
    with:
      rock-name: cos-alerter
      tag-minor: true
